# @package _global_

defaults:
  - /global: default
  - /pipeline: build_manifest
  - /dataset: librispeech
  - _self_

columns:
  utt_id: "{sample.utt_id}"
  path: "{sample.path}"
  split: "{sample.split}"
  spk_id: "{sample.path.parent.parent.stem}"
  transcript: "{sample.resources.transcript.value}"
  # content_path: "{sample.resources.w2vbert.path}"

pipeline:
  overwrite: true

split: train-clean-100

suffix: /${split}
resources_path: outputs/precomputed/${hydra:runtime.choices.dataset}
dataset:
  splits:
    - ${split}
  resource_providers:
    - ${dataset.transcript_provider}
    # - _target_: quick_convert.data.resources.PathResourceProvider
    #   name: w2vbert
    #   kind: torch_tensor
    #   path_template: ${resources_path}/w2vbert/{sample.split}/{sample.utt_id}.pt
  #   - _target_: quick_convert.data.resources.PathResourceProvider
  #     name: spk_espnet
  #     kind: torch_tensor
  #     path_template: ${resources_path}/spk_espnet/{sample.split}/{sample.utt_id}.pt
  #   - _target_: quick_convert.data.resources.PathResourceProvider
  #     name: emo2vec
  #     kind: torch_tensor
  #     path_template: ${resources_path}/emo2vec/{sample.split}/{sample.utt_id}.pt
