# @package _global_

defaults:
  - /global: default
  - /pipeline: build_manifest
  - /dataset: librispeech
  - _self_

columns:
  utt_id: "{sample.utt_id}"
  path: "{sample.path}"
  split: "{sample.split}"
  transcript: "{sample.resources.transcript.value}"
  spkid: "{sample.resources.spkid.value}"

pipeline:
  overwrite: true

split: test-other

suffix: /${split}
resources_path: outputs/precomputed/${hydra:runtime.choices.dataset}
dataset:
  splits:
    - ${split}
  resource_providers:
    - ${dataset.transcript_provider}
    - ${dataset.spkid_provider}
