# @package _global_

defaults:
  - /dataset: clac
  - /asv: ecapa
  - _self_

input_csv_name: dev.csv
output_base_folder: results/asv/
asv_name: ${hydra:runtime.choices.asv}
dataset_name: ${hydra:runtime.choices.dataset}

prep:
  input_csv: ${data.prepared_data_path}/${input_csv_name}
  output_dir: results/asv/eval_${dataset_name}/
  
  # only used if asv.mode is "random"
  enrol_per_speaker: 8
  # enrol_splits:
  #   - cookie_theft
  #   - grandfather
  # test_splits:
  #   - picnic
  #   - rainbow
  #   - smr
  negatives_per_enrol: null
  seed: 1337
  overwrite: false

asv:
  # options: {random, by_split}
  mode: random
  overrides:
    score_norm: null
    pretrain_path: ${asv.overrides.save_folder}