# @package _global_

defaults:
  - /dataset: clac
  - /asv: ecapa
  - _self_

input_csv_name: dev.csv
output_base_folder: results/asv
asv_name: ${hydra:runtime.choices.asv}
dataset_name: ${hydra:runtime.choices.dataset}
suffix: ""

prep:
  input_csv: ${asv.exp_folder}/data/${input_csv_name}
  output_dir: ${asv.exp_folder}/eval

  # only used if asv.mode is "random"
  enrol_per_speaker: 8
  # enrol_splits:
  #   - cookie_theft
  #   - grandfather
  # test_splits:
  #   - picnic
  #   - rainbow
  #   - smr
  negatives_per_enrol: null
  seed: 1337
  overwrite: false

asv:
  # options: {random, by_split}
  mode: random
  overrides:
    pretrain_path: ${asv.overrides.save_folder}
    train_data: ${asv.exp_folder}/data/train.csv
    score_norm: null
