# @package _global_

defaults:
  - /global: default
  - /pipeline: precompute_features
  - /dataset: librispeech
  - /components/feature_extractor@feature_extractor: speaker_embedding
  - /components/speaker_encoder@encoder: espnet
  - _self_

dataset:
  splits:
    - test-other
  load: true
  target_sr: ${encoder.sample_rate}

pipeline:
  out_root: ${out_root}/precomputed/${hydra:runtime.choices.dataset}/${hydra:runtime.choices.components/speaker_encoder@encoder}_{feature_extractor}
