# @package _global_

defaults:
  - /global: default
  - /pipeline: training
  - /trainer: controllable_rvq_v2
  - /dataset@train_dataset: manifest
  - /dataset@val_dataset: manifest
  - /dataset@source_dataset: librispeech
  - /components/ssl@trainer.module.content_encoder: dac
  - _self_

dataset_name: ${hydra:runtime.choices.dataset@source_dataset}
resources_path: outputs/precomputed/${dataset_name}
dataset_path: ${out_root}/${dataset_name}

pipeline:
  batch_size: 2
  train_kwargs:
    val_check_interval: null
    callbacks:
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        save_top_k: 2
        every_n_epochs: 1
        save_last: true
        monitor: step
        mode: max
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        monitor: val/loss
        mode: min
        save_top_k: 1
        save_last: false

trainer:
  train_dataloader_kwargs:
    shuffle: false
  ddp:
    enabled: false
  compile: false
  #   val_dataloader_kwargs:
  #     batch_size: 2

architecture:
  num_feature_layers: 1

data: &data
  resources:
    spkid:
      column: spkid
      kind: text
  max_length: 500000
  resource_providers:
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: token_ids
      name: token_ids
      path_template: ${resources_path}/tokenizer/{sample.split}/{sample.utt_id}.pt
    # - _target_: quick_convert.data.resources.PathResourceProvider
    #   kind: torch_tensor
    #   name: content
    #   path_template: ${resources_path}/w2vbert_6layer/{sample.split}/{sample.utt_id}.pt
    #   max_length: 1000
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: torch_tensor
      name: emo2vec
      path_template: ${resources_path}/emo2vec/{sample.split}/{sample.utt_id}.pt
      max_length: 1000

  load:
    - audio
    - token_ids
    - content
    - emo2vec
    - spk

train_dataset:
  <<: *data
  manifest_path: ${dataset_path}/test-other/manifest.csv
  splits:
    - test-other

val_dataset:
  <<: *data
  manifest_path: ${dataset_path}/test-other/manifest.csv
