# @package _global_

defaults:
  - /global: default
  - /pipeline: training
  - /trainer: vq_asr
  - /dataset@train_dataset: manifest
  - /dataset@val_dataset: manifest
  - /dataset@source_dataset: librispeech
  - _self_

dataset_name: ${hydra:runtime.choices.dataset@source_dataset}
resources_path: outputs/precomputed/${dataset_name}
dataset_path: ${out_root}/${dataset_name}

pipeline:
  batch_size: 2
  dataloader:
    num_workers: 1

trainer:
  train_dataloader_kwargs:
    shuffle: false
  ddp:
    enabled: false
  compile: false
  module:
    commitment_loss_weight: 0.1
    codebook_loss_weight: 0.1

data: &data # compute info from sample
  resources:
    transcript:
      column: transcript
      kind: text
  resource_providers:
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: token_ids
      name: token_ids
      path_template: ${resources_path}/tokenizer/{sample.split}/{sample.utt_id}.pt

  load:
    - audio
    - token_ids

train_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/train_cfs.csv

val_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/val_cfs.csv
