# @package _global_

defaults:
  - /global: default
  - /pipeline: training
  - /trainer: controllable_rvq_v2
  - /dataset@train_dataset: manifest
  - /dataset@val_dataset: manifest
  - /dataset@source_dataset: librispeech
  - _self_

dataset_name: ${hydra:runtime.choices.dataset@source_dataset}
resources_path: outputs/precomputed/${dataset_name}
dataset_path: ${out_root}/${dataset_name}

pipeline:
  batch_size: 64
  train_kwargs:
    val_check_interval: null
    callbacks:
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        monitor: val/decoder/mae

trainer:
  train_dataloader_kwargs:
    shuffle: false

data: &data
  #
  # read info from manifest csv
  resources:
    spkid:
      column: spkid
      kind: text
  max_length: 562480
  # compute info from sample
  resource_providers:
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: token_ids
      name: token_ids
      path_template: ${resources_path}/tokenizer/{sample.split}/{sample.utt_id}.pt
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: torch_tensor
      name: content
      path_template: ${resources_path}/w2vbert_6layer/{sample.split}/{sample.utt_id}.pt
      # precomputed value
      max_length: 1757
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: torch_tensor
      name: emo2vec
      path_template: ${resources_path}/emo2vec/{sample.split}/{sample.utt_id}.pt
      max_length: 1757

  load:
    - audio
    - token_ids
    - content
    - emo2vec
    - spkid

train_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/train.csv

val_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/val.csv
