# @package _global_

defaults:
  - /global: default
  - /pipeline: training
  - /trainer: controllable_rvq
  - /dataset@train_dataset: manifest
  - /dataset@val_dataset: manifest
  - /dataset@source_dataset: librispeech
  - /components/ssl@trainer.module.content_encoder: w2vbert
  - _self_

dataset_name: ${hydra:runtime.choices.dataset@source_dataset}
resources_path: /tmp/u036742/precomputed
dataset_path: ${out_root}/${dataset_name}

pipeline:
  batch_size: 32
  train_kwargs:
    max_epochs: 9
    callbacks:
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        save_top_k: 2
        monitor: step
        mode: max
        every_n_epochs: 1
        save_last: true
        # save_top_k:
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        monitor: val/loss
        mode: min
        save_top_k: 1
        save_last: false

# trainer:
#   train_dataloader_kwargs:
#     shuffle: false

data: &data # read info from manifest csv
  resources:
    spkid:
      column: spkid
      kind: text
  max_length: 562480
  # compute info from sample
  resource_providers:
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: token_ids
      name: token_ids
      path_template: ${resources_path}/tokenizer/{sample.split}/{sample.utt_id}.pt
    - _target_: quick_convert.data.resources.PathResourceProvider
      kind: torch_tensor
      name: emo2vec
      path_template: ${resources_path}/emo2vec/{sample.split}/{sample.utt_id}.pt
      max_length: 1757

  load:
    - audio
    - token_ids
    # - content
    - emo2vec
    - spkid

train_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/train.csv

val_dataset:
  <<: *data
  manifest_path: ${dataset_path}/speaker_split/val.csv
