# configs/pipeline/training.yaml

_target_: quick_convert.pipelines.training.pipeline.TrainingPipeline
trainer: ${trainer}
train_dataset: ${train_dataset}
val_dataset: ${val_dataset}
test_dataset: null
out_dir: ${out_root}/${hydra:runtime.choices.trainer}/${dataset_name}${out_dir_suffix}

batch_size: 8
val_batch_size: ${pipeline.batch_size}

dataloader:
  num_workers: 24
  pin_memory: true
  drop_last: false

train_kwargs:
  # in the future, have the lightning_trainer class interpret more implementation-agnostic
  # param names and translate them into L.Trainer kwargs
  max_steps: -1
  # for step-based validation
  # val_check_interval: 1000
  accelerator: auto
  devices: auto
  precision: 32
  log_every_n_steps: 200
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true

# test_dataset: null
# test_dataloader_kwargs: {}
# run_test: false
