# configs/pipeline/training.yaml

_target_: quick_convert.pipelines.training.pipeline.TrainingPipeline
trainer: ${trainer}
train_dataset: ${train_dataset}
val_dataset: ${val_dataset}
test_dataset: null
out_dir: ${out_root}/${hydra:runtime.choices.trainer}/${dataset_name}${out_dir_suffix}

batch_size: 8
val_batch_size: ${pipeline.batch_size}

dataloader:
  num_workers: 24
  pin_memory: true
  drop_last: false

# test_dataset: null
# test_dataloader_kwargs: {}
# run_test: false
