# this is the one system where the target is an abstraction, i.e. it takes a base trainer type (e.g. `lightning_trainer`)
# and then passes the specific class. It's because these types are redundant, i.e. `controllable_rvq` is always a lightning trainer.

defaults:
  - /global: default
  - /components/encoders@module.encoder: rvq_disentangler
  - /architecture: controllable_rvq
  - /trainer/optimizer@module.optimizer: adamw
  - /trainer/lr_scheduler@module.lr_scheduler: cosine_annealing
  - _self_

_target_: quick_convert.pipelines.training.lightning_trainer.LightningTrainer
module:
  _target_: quick_convert.pipelines.training.modules.ControllableRVQTrainingModule
  decoder: ${architecture.decoder}
  tokenizer:
    _target_: sentencepiece.SentencePieceProcessor
    model_file: ${architecture.tokenizer_model_path}
  decoder_loss_weight: 1.0
  rvq_loss_weights:
    commitment_loss: 1.0
    codebook_loss: 1.0
    mse_loss: 1.0
  distillation_loss_weights:
    ling: 1.0
    spk: 1.0
    emo: 1.0
    pros: 1.0

  adv_loss_weights:
    spk_ling: 1.0
    spk_pros: 1.0
    ling_spk: 1.0
    ling_pros: 1.0
  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 10000
