defaults:
  - /global: default
  - lightning
  - /trainer/optimizer@module.optimization: adamw_cosine
  - _self_

# cudnn, ddp and compile are disabled by default. Switch enabled to true to turn on
cudnn_benchmark: false

ddp:
  enabled: false

compile:
  enabled: false
  targets:
    - decoder

module:
  _target_: quick_convert.pipelines.training.modules.ssl_reconstruction.SSLReconstructionTrainingModule
  decoder: ${architecture.decoder}
  feature_transform: ${architecture.feature_transform}
  online_encoders: ${architecture.online_encoders}
