# trainer/vq_asr.yaml

defaults:
  - /global: default
  # belongs to LightningTrainer base
  - lightning
  - /trainer/optimizer@module.optimization: adamw_cosine

  - _self_

module:
  _target_: quick_convert.pipelines.training.modules.vq_asr.VQASRTrainingModule
  system: ${architecture.system}
  tokenizer_model_path: ${architecture.tokenizer_model_path}
  ctc_loss_weight: 1.
