# trainer/vq_asr.yaml

defaults:
  - /global: default
  # belongs to LightningTrainer base
  - lightning
  - /architecture@_global_.architecture: vq_asr
  - /trainer/optimizer@module.optimizer: adamw
  - _self_

module:
  _target_: quick_convert.pipelines.training.modules.vq_asr.VQASRTrainingModule
  quantizer: ${architecture.quantizer}
  ctc_head: ${architecture.ctc_head}
  layer_fusion: ${architecture.layer_fusion}
  tokenizer_model_path: ${architecture.tokenizer_model_path}
