_target_: quick_convert.components.encoders.ParallelConformerEncoder
input_dim: 1024
embed_dim: 128
num_layers: 24
num_meta_heads: 4
num_sub_heads: 4
ffn_dim: 512
conv_kernel_size: 31
dropout: 0.1
bias: true
pos_emb_base: 10000.0
