_target_: quick_convert.components.encoders.SpeakerASPHead
input_dim: ${architecture.speaker_head.input_dim}
hidden_dim: ${architecture.speaker_head.hidden_dim}
output_dim: ${architecture.speaker_head.output_dim}
supervision: ${architecture.speaker_head.supervision}
loss:
  _target_: quick_convert.components.losses.AAMSoftmaxLoss
  _partial_: true
  in_dim: ${architecture.speaker_head.output_dim}
