# @package architecture

defaults:
  - /components/ssl@content_ssl: w2vbert
  - /components/decoders@decoder: causal_masked_dit
  - _self_

mel_dim: 80
speaker_dim: 192
encoder_dim: 1024

feature_transform:
  _target_: quick_convert.components.layers.layer_fusion.LayerWeightedSum
  num_layers: 24

online_encoders:
  content: ${architecture.content_ssl}
  speaker:
    _target_: quick_convert.components.speaker.speaker_encoders.CosyVoiceCAMPPlusSpeakerEncoder

decoder:
  feature_dim: ${architecture.encoder_dim}
  cond_strategy: null
  flow:
    spk_embed_dim: ${architecture.speaker_dim}
    vocab_size: null
    input_frame_rate: 50
    # number of tokens per mel. 1 if encoder outputs 50hz
    token_mel_ratio: 1
    # decoder:
    #   estimator:
    #     # (len(decoder_routes) + 1 + [cond_strategy?]) * mel_dim
    #     in_channels: ${mul:${add:3,${bool:${architecture.decoder.cond_strategy}}},${architecture.mel_dim}}
