# @package architecture

defaults:
  - /components/ssl@content_ssl: w2vbert
  - /components/decoders@decoder: causal_masked_diff
  - /components/encoders@encoder: rvq_disentangler
  - _self_

mel_dim: 80
speaker_dim: 192
encoder_dim: 1024

feature_transform:
  _target_: quick_convert.components.layers.layer_fusion.LayerWeightedSum
  num_layers: 24

online_encoders:
  content: ${architecture.content_ssl}
  speaker:
    _target_: quick_convert.components.speaker.speaker_encoders.CosyVoiceCAMPPlusSpeakerEncoder

encoder:
  content_encoder:
    input_size: ${architecture.encoder_dim}
  rvq:
    n_codebooks: 8
    codebook_size: 1024
    codebook_dim: 16
    quantizer_dropout: 0.0
  heads: {}
  head_specs: {}
  router:
    _target_: quick_convert.components.layers.routers.DeterministicRVQLayerRouter
    routing: {}

decoder:
  feature_dim: ${architecture.decoder.flow.encoder.output_size}
  cond_strategy: null
  flow:
    spk_embed_dim: ${architecture.speaker_dim}
    vocab_size: null
    input_frame_rate: 50
    # number of tokens per mel. 1 if encoder outputs 50hz
    token_mel_ratio: 1
    encoder:
      do_upsample: false
      upsample_stride: 1
    # decoder:
    #   estimator:
    #     # (len(decoder_routes) + 1 + [cond_strategy?]) * mel_dim
    #     in_channels: ${mul:${add:3,${bool:${architecture.decoder.cond_strategy}}},${architecture.mel_dim}}
