hparams_file: quick_convert/pipelines/asv/hyperparams/train_ecapa_tdnn.yaml
dataset_name: ${hydra:runtime.choices.dataset}
prepared_data_path: results/asv/${asv.dataset_name}_csv
overwrite_csv: false

prep:
    save_folder: ${asv.prepared_data_path}
    train_fraction: 0.8
    # train_splits: ${dataset.splits}
    # dev_splits: []
    randomize_within_split: false
    seed: 1337

overrides:
    output_folder: results/asv/ecapa_${asv.dataset_name}
    save_folder: results/asv/ecapa_${asv.dataset_name}/save
    data_folder: /unused/by_custom_prep
    skip_prep: true
    dataloader_options:
        drop_last: true
