hparams_file: quick_convert/pipelines/asv/hyperparams/train_ecapa_tdnn.yaml
prepared_data_path: ${output_base_folder}/${dataset_name}_csv
overwrite_csv: false

prep:
    save_folder: ${asv.prepared_data_path}
    train_fraction: 0.9
    # train_splits: ${dataset.splits}
    # dev_splits: []
    randomize_within_split: false
    seed: 1337

overrides:
    output_folder: ${output_base_folder}/${asv_name}_${dataset_name}
    save_folder: ${output_base_folder}/${asv_name}_${dataset_name}/save
    data_folder: /unused/by_custom_prep
    skip_prep: true
