# @package architecture
# configs/architecture/controllable_rvq.yaml

defaults:
  - /components/ssl@emotion_ssl: emo2vec
  - /components/ssl@content_ssl: w2vbert
  - /components/speaker_encoder@speaker_ssl: espnet
  - /components/decoders@decoder: chatterbox
  - /components/layers@rvq: rvq
  - /components/encoders@decoder.flow.encoder: conformer_encoder
  - _self_

# probably won't need more than 256
encoder_dim: 256

tokenizer_model_path: outputs/tokenizer/librispeech_1000_tokens/tokenizer.model
tokenizer_vocab_size: 1000

feature_extractors:
  content: ${architecture.content_ssl}
  emotion: ${architecture.emotion_ssl}
  speaker: ${architecture.speaker_ssl}

content_encoder:
  input_dim: ${architecture.content_ssl.feature_dim}
  embed_dim: ${architecture.encoder_dim}

rvq:
  input_dim: ${architecture.content_encoder.embed_dim}
  n_codebooks: 8
  codebook_size: 1024
  codebook_dim: 16
  quantizer_dropout: 0.0

# rvq_dim: ${mul:${architecture.rvq.n_codebooks},${architecture.rvq.codebook_dim}}

emotion_head:
  _target_: quick_convert.components.encoders.LinearHead
  input_dim: ${architecture.rvq.input_dim}
  output_dim: ${architecture.feature_extractors.emotion.feature_dim}

linguistic_head:
  hidden_dim: ${architecture.rvq.input_dim}
  output_dim: ${architecture.tokenizer_vocab_size}
speaker_head:
  input_dim: ${architecture.rvq.input_dim}
  hidden_dim: 256
  output_dim: ${architecture.feature_extractors.speaker.feature_dim}
  supervision: aam

prosody_head: null
# _target_: quick_convert.components.encoders.LinearHead
# input_dim: ${architecture.ssl_dim}
# output_dim: ${architecture.emotion_dim}

sample_rate: 16000

# content:
#   input_dim: ${architecture.content_ssl.feature_dim}
#   embed_dim: ${architecture.encoder_dim}

# ssl_dim: 1024
# content_dim: 512
# hidden_dim: 512

# num_quantizers: 8
# codebook_size: 1024

# linguistic_dim: 512
# speaker_dim: 192
# emotion_dim: 768
# prosody_dim: 128

mel_dim: 80

decoder:
  cond_strategy: null
  flow:
    vocab_size: null
    encoder:
      num_blocks: 6
      embed_dim: 256
      # hardcoded for now. 2 because ling_q +  emo_pros_q
      input_dim: ${mul:2,${architecture.encoder_dim}}
    decoder:
      estimator:
        in_channels: ${mul:${add:3,${bool:${architecture.decoder.cond_strategy}}},${architecture.mel_dim}}
