# @package architecture

defaults:
  - /components/ssl@content_ssl: w2vbert
  - /components/speaker_encoder@speaker_encoder: campplus
  # - /components/layers@feature_transform: layer_fusion
  - /components/decoders@decoder: chatterbox
  - /components/encoders@decoder.flow.encoder: conformer_encoder
  - _self_

mel_dim: 80
speaker_dim: 192
encoder_dim: 1024

feature_transform:
  _target_: quick_convert.components.layers.layer_fusion.LayerWeightedSum
  num_layers: 24

online_encoders:
  content: ${architecture.content_ssl}
  speaker: ${architecture.speaker_encoder}

decoder:
  cond_strategy: null
  flow:
    spk_embed_dim: ${architecture.speaker_dim}
    vocab_size: null
    encoder:
      num_blocks: 6
      embed_dim: 256
      # hardcoded for now. 2 because ling_q +  emo_pros_q
      input_dim: ${architecture.encoder_dim}
    decoder:
      estimator:
        # (len(decoder_routes) + 1 + [cond_strategy?]) * mel_dim
        in_channels: ${mul:${add:3,${bool:${architecture.decoder.cond_strategy}}},${architecture.mel_dim}}
