# @package _global_
# configs/dataset/librispeech.yaml

_target_: quick_convert.data.BaseDataset
root: ${data_root}/librispeech/Librispeech
splits:
  - train-clean-100
  - train-clean-360
  - train-other-500
  - dev-clean
  - dev-other
  - test-clean
  - test-other

file_format: flac
utt_id_template: "{path.stem}"

# i put **kwargs into the base_dataset constructor so this wouldn't throw an error but I'm
# not in love with that resolution
transcript_provider:
  _target_: quick_convert.data.resources.CSVTranscriptProvider
  path_template: "{path.parent}/{path.parent.parent.name}-{path.parent.name}.trans.txt"
  utterance_key: path.stem
  key_column: 0
  text_column: 1
  delimiter: " "
  join_text_columns: true

spkid_provider:
  _target_: quick_convert.data.resources.TemplateResourceProvider
  kind: text
  name: spkid
  template: "{path.parent.parent.name}"
