# @package system

defaults:
  - /components/encoders@ctc_head: linguistic_head
  - /components/layers@quantizer: rvq_ema
  - /components/ssl@online_encoders.content: w2vbert
  - _self_

_target_: quick_convert.systems.asr.VQASRSystem
quantizer:
  input_dim: ${system.online_encoders.content.feature_dim}
  n_codebooks: 1
  codebook_dim: 256
  codebook_size: 64
layer_fusion:
  _target_: quick_convert.components.layers.LayerWeightedSum
  num_layers: 24
ctc_head:
  input_dim: 256
  output_dim: 1000
