# configs/run/infer_controllable_rvq_dac.yaml
defaults:
  - /global: default
  # - /architecture: controllable_rvq
  # - /components/ssl@content_encoder: w2vbert
  - _self_

_target_: quick_convert.pipelines.training.modules.ControllableRVQTrainingModule
encoder: ${architecture.encoder}
decoder: ${architecture.decoder}
tokenizer_pad_id: 0
