# @package system

defaults:
  - /components/ssl@online_encoders.content: w2vbert
  - /components/decoders@decoder: causal_masked_diff
  - _self_

_target_: quick_convert.systems.reconstruction.SSLReconstructionSystem
feature_transform:
  _target_: quick_convert.components.layers.layer_fusion.LayerWeightedSum
  num_layers: 24
online_encoders:
  speaker:
    _target_: quick_convert.components.speaker.speaker_encoders.CosyVoiceCAMPPlusSpeakerEncoder
decoder:
  feature_dim: 1024
  cond_strategy: null
  flow:
    spk_embed_dim: 192
    vocab_size: null
    input_frame_rate: 50
    token_mel_ratio: 1
    encoder:
      do_upsample: false
      upsample_stride: 1
